export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.15" };
  public: {
    Tables: {
      brands: { Row: { created_at: string; id: number; name: string; updated_at: string }; Insert: { created_at?: string; id?: never; name: string; updated_at?: string }; Update: { created_at?: string; id?: never; name?: string; updated_at?: string }; Relationships: [] };
      customers: { Row: { city: string; created_at: string; id: number; name: string; phone: string; updated_at: string }; Insert: { city: string; created_at?: string; id?: never; name: string; phone: string; updated_at?: string }; Update: { city?: string; created_at?: string; id?: never; name?: string; phone?: string; updated_at?: string }; Relationships: [] };
      credit_note_idempotency_keys: {
        Row: { created_at: string; credit_note_id: number | null; id: number; idempotency_key: string; operation: string; principal_scope: string; request_fingerprint: string };
        Insert: { created_at?: string; credit_note_id?: number | null; id?: never; idempotency_key: string; operation: string; principal_scope: string; request_fingerprint: string };
        Update: { created_at?: string; credit_note_id?: number | null; id?: never; idempotency_key?: string; operation?: string; principal_scope?: string; request_fingerprint?: string };
        Relationships: [{ foreignKeyName: "credit_note_idempotency_keys_credit_note_id_fkey"; columns: ["credit_note_id"]; isOneToOne: false; referencedRelation: "credit_notes"; referencedColumns: ["id"] }];
      };
      credit_note_items: {
        Row: { created_at: string; credit_note_id: number; cogs_reversal_total: number; id: number; invoice_item_id: number; line_total: number; product_id: number; quantity: number; unit: string; unit_cost: number; unit_price: number; warehouse_id: number };
        Insert: { created_at?: string; credit_note_id: number; cogs_reversal_total: number; id?: never; invoice_item_id: number; line_total: number; product_id: number; quantity: number; unit: string; unit_cost: number; unit_price: number; warehouse_id: number };
        Update: { created_at?: string; credit_note_id?: number; cogs_reversal_total?: number; id?: never; invoice_item_id?: number; line_total?: number; product_id?: number; quantity?: number; unit?: string; unit_cost?: number; unit_price?: number; warehouse_id?: number };
        Relationships: [
          { foreignKeyName: "credit_note_items_credit_note_id_fkey"; columns: ["credit_note_id"]; isOneToOne: false; referencedRelation: "credit_notes"; referencedColumns: ["id"] },
          { foreignKeyName: "credit_note_items_invoice_item_id_fkey"; columns: ["invoice_item_id"]; isOneToOne: false; referencedRelation: "invoice_items"; referencedColumns: ["id"] },
          { foreignKeyName: "credit_note_items_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] },
          { foreignKeyName: "credit_note_items_warehouse_id_fkey"; columns: ["warehouse_id"]; isOneToOne: false; referencedRelation: "warehouses"; referencedColumns: ["id"] }
        ];
      };
      credit_notes: {
        Row: { created_at: string; credit_date: string; credit_note_number: string; currency_code: string; customer_id: number; grand_total: number; id: number; invoice_id: number; notes: string | null; reason: string; status: string; subtotal: number; updated_at: string };
        Insert: { created_at?: string; credit_date: string; credit_note_number: string; currency_code: string; customer_id: number; grand_total: number; id?: never; invoice_id: number; notes?: string | null; reason: string; status: string; subtotal: number; updated_at?: string };
        Update: { created_at?: string; credit_date?: string; credit_note_number?: string; currency_code?: string; customer_id?: number; grand_total?: number; id?: never; invoice_id?: number; notes?: string | null; reason?: string; status?: string; subtotal?: number; updated_at?: string };
        Relationships: [
          { foreignKeyName: "credit_notes_customer_id_fkey"; columns: ["customer_id"]; isOneToOne: false; referencedRelation: "customers"; referencedColumns: ["id"] },
          { foreignKeyName: "credit_notes_invoice_id_fkey"; columns: ["invoice_id"]; isOneToOne: false; referencedRelation: "invoices"; referencedColumns: ["id"] }
        ];
      };
      customer_payment_allocations: { Row: { amount: number; created_at: string; id: number; invoice_id: number; payment_id: number }; Insert: { amount: number; created_at?: string; id?: never; invoice_id: number; payment_id: number }; Update: { amount?: number; created_at?: string; id?: never; invoice_id?: number; payment_id?: number }; Relationships: [{ foreignKeyName: "customer_payment_allocations_invoice_id_fkey"; columns: ["invoice_id"]; isOneToOne: false; referencedRelation: "invoices"; referencedColumns: ["id"] }, { foreignKeyName: "customer_payment_allocations_payment_id_fkey"; columns: ["payment_id"]; isOneToOne: false; referencedRelation: "customer_payments"; referencedColumns: ["id"] }] };
      customer_payment_idempotency_keys: { Row: { created_at: string; id: number; idempotency_key: string; operation: string; payment_id: number | null; principal_scope: string; request_fingerprint: string }; Insert: { created_at?: string; id?: never; idempotency_key: string; operation: string; payment_id?: number | null; principal_scope: string; request_fingerprint: string }; Update: { completed_at?: string | null; created_at?: string; idempotency_key?: string; operation?: string; payment_id?: number | null; principal_scope?: string; request_fingerprint?: string }; Relationships: [{ foreignKeyName: "customer_payment_idempotency_keys_payment_id_fkey"; columns: ["payment_id"]; isOneToOne: false; referencedRelation: "customer_payments"; referencedColumns: ["id"] }] };
      customer_payments: { Row: { amount: number; created_at: string; currency_code: string; customer_id: number; id: number; notes: string | null; payment_date: string; payment_method: string; reference_number: string | null; updated_at: string }; Insert: { amount: number; created_at?: string; currency_code: string; customer_id: number; id?: never; notes?: string | null; payment_date: string; payment_method: string; reference_number?: string | null; updated_at?: string }; Update: { amount?: number; created_at?: string; currency_code?: string; customer_id?: number; id?: never; notes?: string | null; payment_date?: string; payment_method?: string; reference_number?: string | null; updated_at?: string }; Relationships: [{ foreignKeyName: "customer_payments_customer_id_fkey"; columns: ["customer_id"]; isOneToOne: false; referencedRelation: "customers"; referencedColumns: ["id"] }] };
      inventory: { Row: { created_at: string; id: number; product_id: number; quantity: number; updated_at: string; warehouse_id: number }; Insert: { created_at?: string; id?: number; product_id: number; quantity?: number; updated_at?: string; warehouse_id: number }; Update: { created_at?: string; id?: number; product_id?: number; quantity?: number; updated_at?: string; warehouse_id?: number }; Relationships: [{ foreignKeyName: "inventory_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] }, { foreignKeyName: "inventory_warehouse_id_fkey"; columns: ["warehouse_id"]; isOneToOne: false; referencedRelation: "warehouses"; referencedColumns: ["id"] }] };
      products: { Row: { brand_id: number | null; category: string; created_at: string; id: number; name: string; purchase_price: number; sale_price: number; sku: string; unit: string; updated_at: string }; Insert: { brand_id?: number | null; category: string; created_at?: string; id?: never; name: string; purchase_price: number; sale_price: number; sku: string; unit: string; updated_at?: string }; Update: { brand_id?: number | null; category?: string; created_at?: string; id?: never; name?: string; purchase_price?: number; sale_price?: number; sku?: string; unit?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "products_brand_id_fkey"; columns: ["brand_id"]; isOneToOne: false; referencedRelation: "brands"; referencedColumns: ["id"] }] };
      purchase_idempotency_keys: { Row: { completed_at: string | null; created_at: string; expires_at: string; id: number; idempotency_key: string; operation: string; principal_scope: string; purchase_id: number | null; request_fingerprint: string; response_body: Json | null; response_status: number | null; status: string }; Insert: { completed_at?: string | null; created_at?: string; expires_at?: string; id?: never; idempotency_key: string; operation: string; principal_scope: string; purchase_id?: number | null; request_fingerprint: string; response_body?: Json | null; response_status?: number | null; status?: string }; Update: { completed_at?: string | null; created_at?: string; expires_at?: string; id?: never; idempotency_key?: string; operation?: string; principal_scope?: string; purchase_id?: number | null; request_fingerprint?: string; response_body?: Json | null; response_status?: number | null; status?: string }; Relationships: [{ foreignKeyName: "purchase_idempotency_keys_purchase_id_fkey"; columns: ["purchase_id"]; isOneToOne: false; referencedRelation: "purchases"; referencedColumns: ["id"] }] };
      purchase_items: { Row: { created_at: string; id: number; product_id: number; purchase_id: number; quantity: number; total_cost: number; unit_cost: number; updated_at: string }; Insert: { created_at?: string; id?: number; product_id: number; purchase_id: number; quantity: number; total_cost: number; unit_cost: number; updated_at?: string }; Update: { created_at?: string; id?: never; product_id?: number; purchase_id?: number; quantity?: number; total_cost?: number; unit_cost?: number; updated_at?: string }; Relationships: [{ foreignKeyName: "purchase_items_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] }, { foreignKeyName: "purchase_items_purchase_id_fkey"; columns: ["purchase_id"]; isOneToOne: false; referencedRelation: "purchases"; referencedColumns: ["id"] }] };
      purchases: { Row: { created_at: string; discount: number; id: number; invoice_number: string | null; notes: string | null; purchase_date: string; subtotal: number; tax: number; total: number; updated_at: string; vendor_id: number; warehouse_id: number }; Insert: { created_at?: string; discount?: number; id?: number; invoice_number?: string | null; notes?: string | null; purchase_date?: string; subtotal?: number; tax?: number; total?: number; updated_at?: string; vendor_id: number; warehouse_id: number }; Update: { created_at?: string; discount?: number; id?: number; invoice_number?: string | null; notes?: string | null; purchase_date?: string; subtotal?: number; tax?: number; total?: number; updated_at?: string; vendor_id?: number; warehouse_id?: number }; Relationships: [{ foreignKeyName: "purchases_vendor_id_fkey"; columns: ["vendor_id"]; isOneToOne: false; referencedRelation: "vendors"; referencedColumns: ["id"] }, { foreignKeyName: "purchases_warehouse_id_fkey"; columns: ["warehouse_id"]; isOneToOne: false; referencedRelation: "warehouses"; referencedColumns: ["id"] }] };
      stock_movements: { Row: { created_at: string; id: number; movement_type: string; notes: string | null; product_id: number; quantity: number; reference_id: number | null; reference_type: string | null; unit_cost: number | null; warehouse_id: number }; Insert: { created_at?: string; id?: never; movement_type: string; notes?: string | null; product_id: number; quantity: number; reference_id?: number | null; reference_type?: string | null; unit_cost?: number | null; warehouse_id: number }; Update: { created_at?: string; id?: never; movement_type?: string; notes?: string | null; product_id?: number; quantity?: number; reference_id?: number | null; reference_type?: string | null; unit_cost?: number | null; warehouse_id?: number }; Relationships: [{ foreignKeyName: "stock_movements_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] }, { foreignKeyName: "stock_movements_warehouse_id_fkey"; columns: ["warehouse_id"]; isOneToOne: false; referencedRelation: "warehouses"; referencedColumns: ["id"] }] };
      vendors: { Row: { city: string; created_at: string; id: number; name: string; phone: string; updated_at: string }; Insert: { city: string; created_at?: string; id?: never; name: string; phone: string; updated_at?: string }; Update: { city?: string; created_at?: string; id?: never; name?: string; phone?: string; updated_at?: string }; Relationships: [] };
      warehouses: { Row: { created_at: string; id: number; location: string | null; name: string; updated_at: string }; Insert: { created_at?: string; id?: never; location?: string | null; name: string; updated_at?: string }; Update: { city?: string; created_at?: string; id?: never; location?: string | null; name?: string; updated_at?: string }; Relationships: [] };
    };
    Views: Record<never, never>;
    Functions: {
      record_purchase: { Args: { p_discount?: number; p_idempotency_key: string; p_idempotency_operation: string; p_idempotency_principal: string; p_invoice_number?: string; p_items: Json; p_notes?: string; p_purchase_date?: string; p_request_fingerprint: string; p_tax?: number; p_vendor_id: number; p_warehouse_id: number }; Returns: Json };
      record_customer_payment: { Args: { p_customer_id: number; p_payment_date: string; p_amount: number; p_currency_code: string; p_payment_method: string; p_reference_number?: string | null; p_notes?: string | null; p_allocations?: Json; p_principal_scope?: string; p_operation?: string; p_idempotency_key?: string | null; p_request_fingerprint?: string | null }; Returns: Json };
      record_sales_return: { Args: { p_credit_note_number: string; p_invoice_id: number; p_customer_id: number; p_credit_date: string; p_currency_code: string; p_reason: string; p_notes?: string | null; p_items: Json; p_principal_scope: string; p_operation: string; p_idempotency_key: string; p_request_fingerprint: string }; Returns: Json };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
