import { buildAiReview } from "./ai-experience.js";
import { signIn, getSession, signOut } from "./auth.js";
import { createCopilotDraft, confirmCopilotDraft } from "./copilot-api.js";

const sections = [["dashboard","Dashboard"],["customers","Customers"],["vendors","Vendors"],["products","Products"],["warehouses","Warehouses"],["inventory","Inventory"],["purchases","Purchases"],["estimates","Estimates"],["invoices","Invoices"],["returns","Returns"],["payments","Payments"],["rates","Rate Lists"],["accounting","Accounting"],["reports","Reports"]];
const nav = document.querySelector("#nav"); const content = document.querySelector("#content"); const title = document.querySelector("#page-title"); const shell = document.querySelector(".app-shell");
let authenticatedUserId = null; let activeDraft = null;
function renderNav(active){nav.replaceChildren(...sections.map(([id,label])=>{const button=document.createElement("button");button.className=`nav-item${id===active?" active":""}`;button.textContent=label;button.type="button";button.addEventListener("click",()=>navigate(id));return button;}));}
function card(label,value,note){return `<article class="card"><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="muted">${note}</div></article>`;}
function table(titleText,columns,rows){return `<div class="section-head"><h2>${titleText}</h2><button class="button secondary" type="button">View all</button></div><div class="card table-wrap"><table class="table"><thead><tr>${columns.map(c=>`<th>${c}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function dashboard(){return `<div class="grid stats">${card("Sales today","—","Connect live sales data")}${card("Receivables","—","Connect live customer balances")}${card("Stock value","—","Connect live inventory valuation")}${card("Gross profit","—","Connect live accounting data")}</div><div class="section-head"><h2>Quick actions</h2></div><div class="grid quick-grid">${[["New Estimate","Start a customer estimate"],["New Invoice","Create a sales invoice"],["Record Purchase","Post supplier stock"],["AI Copilot","Describe an ERP task"],["Customer Payment","Record a receipt"],["Stock Adjustment","Review inventory movement"]].map(([a,b])=>`<button class="card quick-action" data-ai-action="${a==="AI Copilot"?"copilot":""}" type="button"><strong>${a}</strong><span class="muted">${b}</span></button>`).join("")}</div>${table("Recent activity",["Reference","Type","Customer / Vendor","Amount","Status"],[["—","—","Connect live ERP data","—",'<span class="badge">Ready</span>']])}`;}
function generic(label){return `<div class="card"><div class="section-head"><div><p class="eyebrow">ERP workspace</p><h2>${label}</h2></div><button class="button primary" type="button">+ New ${label.slice(0,-1)||label}</button></div><p class="muted">This production surface uses the authoritative ERP service boundary. Financial, inventory, pricing and transaction rules remain on the backend.</p></div>${table(`Recent ${label.toLowerCase()}`, ["ID","Name / Reference","Status","Updated"], [["—","Ready for live data","Connected",new Date().toLocaleDateString()]])}`;}
function navigate(id){const label=sections.find(([section])=>section===id)?.[1]??"Dashboard";title.textContent=label;renderNav(id);content.innerHTML=id==="dashboard"?dashboard():generic(label);shell.classList.remove("menu-open");document.querySelectorAll("[data-ai-action='copilot']").forEach(el=>el.addEventListener("click",()=>dialog.showModal()));}
function value(id){return document.querySelector(id)?.value.trim()||"";}
function numberOrUndefined(id){const raw=value(id);if(!raw)return undefined;const parsed=Number(raw);if(!Number.isFinite(parsed)||parsed<=0)throw new Error(`${id} must be a positive number`);return parsed;}
function actionIntent(){const action=value("#copilot-action");return action==="purchase"?"supplier_bill":action==="return"?"customer_return":action;}
function resetDraft(){activeDraft=null;document.querySelector("#copilot-confirm").hidden=true;document.querySelector("#copilot-run").hidden=false;}

const dialog=document.querySelector("#copilot"); const result=document.querySelector("#copilot-result");
document.querySelector("#menu").addEventListener("click",()=>shell.classList.toggle("menu-open"));
document.querySelector("#copilot-button").addEventListener("click",()=>{resetDraft();dialog.showModal();});
document.querySelector("#copilot-close").addEventListener("click",()=>dialog.close());
document.querySelector("#copilot-action").addEventListener("change",resetDraft);
document.querySelector("#copilot-run").addEventListener("click",async()=>{try{
  if(!authenticatedUserId)throw new Error("Sign in before using AI Copilot.");
  const organizationId=value("#copilot-organization"); const productId=numberOrUndefined("#copilot-product"); const quantity=numberOrUndefined("#copilot-quantity");
  if(!organizationId)throw new Error("Organization ID is required."); if(!productId)throw new Error("Product ID is required for a transaction draft."); if(!quantity)throw new Error("Quantity must be greater than zero.");
  const explicitRate=numberOrUndefined("#copilot-rate"); const rateListId=numberOrUndefined("#copilot-rate-list"); const action=actionIntent();
  const review=buildAiReview({text:value("#copilot-input"),action: value("#copilot-action"),rateListId:rateListId?String(rateListId):null,inputType:"text"});
  const lines=[{productName:review.instruction,productId,quantity,unit:"pcs",...(explicitRate!==undefined?{unitRate:explicitRate}: {})}];
  const payload={organizationId,intent:action,source:"text",customerId:value("#copilot-customer")||undefined,vendorId:value("#copilot-vendor")||undefined,warehouseId:numberOrUndefined("#copilot-warehouse"),rateListId,documentNumber:value("#copilot-document")||undefined,reason:value("#copilot-reason")||undefined,lines,confidence:1};
  const response=await createCopilotDraft(payload); activeDraft={id:response.data.id,organizationId,idempotencyKey:response.data.idempotency_key};
  result.hidden=false;result.textContent=`DRAFT CREATED\n\n${JSON.stringify(response.data,null,2)}\n\nReview complete. Explicit confirmation is required before execution.`;document.querySelector("#copilot-run").hidden=true;document.querySelector("#copilot-confirm").hidden=false;
}catch(error){result.hidden=false;result.textContent=error instanceof Error?error.message:"Unable to create Copilot draft.";}});
document.querySelector("#copilot-confirm").addEventListener("click",async()=>{try{if(!activeDraft||!authenticatedUserId)throw new Error("No authenticated Copilot draft is ready for confirmation.");const response=await confirmCopilotDraft({id:activeDraft.id,organizationId:activeDraft.organizationId,userId:authenticatedUserId,idempotencyKey:activeDraft.idempotencyKey});result.hidden=false;result.textContent=`${response.executed?"EXECUTED":"NOT EXECUTED"}\n\n${JSON.stringify(response.data,null,2)}`;document.querySelector("#copilot-confirm").hidden=true;activeDraft=null;}catch(error){result.hidden=false;result.textContent=error instanceof Error?error.message:"Unable to confirm Copilot action.";}});

const authDialog=document.querySelector("#auth-dialog");const authButton=document.querySelector("#auth-button");const authResult=document.querySelector("#auth-result");
authButton.addEventListener("click",()=>authDialog.showModal());document.querySelector("#auth-close").addEventListener("click",()=>authDialog.close());
document.querySelector("#auth-submit").addEventListener("click",async()=>{try{const session=await signIn(value("#auth-email"),value("#auth-password"));authenticatedUserId=session.user?.id??null;authResult.hidden=false;authResult.textContent="Authenticated ERP session established.";authButton.textContent="Signed in";document.querySelector("#auth-signout").hidden=false;}catch(error){authResult.hidden=false;authResult.textContent=error instanceof Error?error.message:"Unable to sign in.";}});
document.querySelector("#auth-signout").addEventListener("click",async()=>{await signOut();authenticatedUserId=null;authButton.textContent="Sign in";document.querySelector("#auth-signout").hidden=true;authResult.hidden=false;authResult.textContent="Signed out.";resetDraft();});
getSession().then(session=>{authenticatedUserId=session?.data?.userId??null;authButton.textContent=authenticatedUserId?"Signed in":"Sign in";}).catch(()=>{authenticatedUserId=null;});
navigate("dashboard");
